### ISSUE TITLE
exports.awaitMessages

### ISSUE THREAD

**Issue by SomeoneCares11** [minemidnight/oxyl#9]
exports.awaitMessages = async (channel, filter, options) => {
                              ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/test/oxyl/oxyl.js:2:20)
    at Module._compile (module.js:570:32)

**Comment by minemidnight** [comment]
well if you're trying to host the bot, you need to run it with --harmony and node v7 or higher
